import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import '../style.css'
import PlayerPane from "../components/PlayerPane/PlayerPane";
import NavBar from "../components/NavBar/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
        <PlayerPane />
        <section className="wrapper">
          <NavBar />
          {children}
        </section>
    </>
  );
}
