import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import '../style.css'
import PlayerPane from "../components/PlayerPane/PlayerPane";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="min-h-full flex flex-col relative">
        <PlayerPane />
        <section className="wrapper">
        {children}
        </section>
      </body>
    </html>
  );
}
